name: Unit Tests
uses: mattallty/jest-github-action@v1

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITLAB_URL: ${{ secrets.GITLAB_URL }}
  GITLAB_ACCESS_TOKEN: ${{ GITLAB_ACCESS_TOKEN }}

on: [push, pull_request]

with:
  test-command: "npm run test:ci"
