name: Unit Tests

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITLAB_URL: ${{ secrets.GITLAB_URL }}
  GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}

on: [push, pull_request]

jobs:
  tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run test:ci
